def my_name():
    return "Matas"
def char_name():
    return "John"
def part5():
    return "John was a regular 3rd year student at University of Amsterdam. Although he was already familiar with the housing issues present in the city, he was taken by surprise when every landlord advertising their place refused to even pick up his calls. Frustrated, he ransacked Marktplaats at the last minute to find any type of solution, as sleeping below the bridge was not an option. Luckily, John discovered a cabin in a dense forest just behind Amsterdam for rent. Albeit ominous and definitely cursed, it was cheap and with registration, so John took the offer immediately and set out to view his new place. Surprisingly, there were other people already present near the cabin, waiting for something. After asking some of these wanderers,  something did not add up: Scarlet arrived there expecting a party, others like Lukas, Phoenix and Charlie wandered upon this place based on faint stories, and Monica was just taking pictures. Even though he felt a hint of danger and deception, John stayed, as something within the cabin had already drawn his attention."
def part11():
    return "While others were scavenging the first floot, John decided to go upstairs to take a look around and figure out the reason behind the advertisement and the group of people that showed up alongside him. As he stepped inside one of the bedrooms, he was anxious by the flickering lights that soon went out, further frustrating him. Slowky and carefully, John moved around the room, trying to find any source of light. His luck finally took a turn for the better, as he managed to find a flashlight on the cupboard. However, luck again took a nosedive after the flashlight was found to have no batteries. After finding a few useful tools and supplies, John looked at the wall and found a rather disturbing medieval painting of this cabin covered in blood and guts. Below the cabin were some written words, which upon further inspection spelled out “Monica, Lukas, Phoenix, Scarlet, John, Charlie”. Creeped out by this revelation, he decided that this rent contract is not worth it, and hastily left the room. Running down the stairs, John was confronted by some of the people from the outside, who were yelling over each other, demanding questions about something concerning a murder. With a clueless expression, he asked what had happened and why is everyone mad at him."
def part17():
    return "John and Charlie looked at each other with panic and suspicion. After a string of chaotic events that resulted in Monica, Lukas, Phoenix and Scarlet dealhs, both were as scared as ready to lunge at each other. Suddenly and without a warning, John took a nearby ax that he took from the second floor and began wildly swinging it at Charlie. Although not looking like it, Charlie was agile and quickly took the initiative of the fight by avoiding the first swings. Eventually, John got into a clash with Charlie, who with a bit of effort managed to disarm him. The last thing that John saw was an ax head falling on his head."