import Angelica, Angeline, caleb, Paula, file

def MyName():
   return "Raven"

def my_character():
   return "Charlie"

def par6():
   return "Father Markus had always described the scenery as plain on his treks through the green hills. Charlie did not know his way around the area but he figured the old priest took nature for granted too often. Perhaps it was an undiscovered gem Charlie could use to decompress. After his semester at the university finally ended he decided to check it out for himself, see whether it was truly such a drab place. The forest appeared nondescript but peaceful when he entered it and he hoisted his bag higher up his back and followed the single trail into the woods. For a while, he couldn’t make out much aside from a large variety of thick pine trees, towering over him and blocking out the majority of the light. Even though it was only early afternoon, it appeared late already. Who knows how much time had passed when Charlie came across an odd-looking structure, a cabin, large enough to house a family. Light poured out from the dust-covered windows. Despite it looking like it hadn’t been lived in for a very long time, noise could be heard from the entrance. Trepidation filled Charlie’s stomach as he stared at the list haphazardly nailed to the door. Amongst the names of strangers was his own name, written in the ugliest handwriting, “Monica, Lukas, Phoenix, Scarlet, John, and Charlie.”"

def par12():
   return "All of a sudden the room grew quiet when the missing group member had returned. John’s return to the group had brought both relief and a quiet mistrust. Despite everyone’s name being on that godforsaken list, no one knew each other, and the connection between everyone was far to be found. The group became tenser by the second, even as some attempted to mitigate the growing conflict. Phoenix, the young detective was bursting with energy, rambling on about a letter from an unidentified author requesting he come here. According to him, this specific group was no coincidence, but it didn’t make sense. Scarlet avoided John whenever possible, having already accused him of nefarious activities. John naturally denied all accusations, reasoning that his trip to the upstairs floor could not possibly be chalked up to anything other than curiosity. He spoke of troubling imagery, a painting of the cabin that seemed to bleed. Charlie wanted to suggest that Monica go upstairs to check it out when they heard a blood-curdling scream from the other room. Lukas ran into the room and returned swiftly with a pale face, claiming Monica was dead."

def par18(): 
   return f"Charlie slowly removed the bloody axe from John’s forehead, his eye split in half at the part the blade cut through. Nausea and panic had been building up in his stomach throughout the night but seeing John’s lifeless form sent him over the edge. His body convulsed, hacking up what little he had eaten in the past few hours to pile up in a shapeless heap next to the body. He trembled at the knowledge of what he had done. This all went terribly so quickly! Looking around the empty room, Charlie wondered how he got here and what had happened to turn this day into such a nightmare. At least he managed to kill the killer, he thought somberly. Just when he was about to exit the crime scene a hand sneaked up behind him and a knife pressed to his throat. A familiar voice spoke in hushed tones, “As derived from John 11:25-26 ‘Jesus said to her, “I am the resurrection and the life. The one who believes in me will live, even though they die; and whoever lives by believing in me will never die. Do you believe this?’ No one ever truly dies. So spoke the lord.” The knife slashed Charlie’s throat and his knees buckled, blood flowing down his shirt and sputtering his last breath. At last, the list had been completed: Monica, {caleb.my_character()}, Phoenix, Scarlet, John, and Charlie."
    